# Site settings
title: Women in Computer Science @ Columbia University
email: cu.wics@gmail.com
author: WiCS@CU
description: > # this means to ignore newlines until "baseurl:"
  WiCS aims to bring together women and men who support the advancement of women in computer science in academia and in industry. We support and encourage prospective computer science majors and provide direction and assistance to current computer science students. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cuwics.github.io" # the base hostname & protocol for your site
twitter_username: cu_wics
github_username:  cuwics

# Build settings
markdown: kramdown
permalink: pretty

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
